# Generated by Django 6.0.4 on 2026-04-23 07:52

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('f_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('f_village', models.CharField(max_length=100)),
                ('f_email', models.EmailField(max_length=254)),
                ('f_password', models.CharField(max_length=100)),
            ],
        ),
    ]
