# Generated by Django 6.0.4 on 2026-04-24 10:55

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_type', models.CharField(choices=[('customer', 'Local Customer'), ('retailer', 'Shopkeeper / Retailer'), ('wholesaler', 'Wholesaler')], max_length=20)),
                ('b_name', models.CharField(max_length=100)),
                ('b_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('b_location', models.CharField(max_length=100)),
                ('b_email', models.EmailField(max_length=254)),
                ('b_password', models.CharField(max_length=100)),
            ],
        ),
    ]
